#!/usr/bin/env bash

DRIVER_ARGS="$@"

if [ "$DRIVER_ARGS" == "" ]; then
	DRIVER_ARGS="-d virtualbox"
fi

function getInternalIp() {
	if [[ $DRIVER_ARGS == *virtualbox* ]]; then
		docker-machine ip $1
	else
		docker-machine ssh $1 ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'
	fi
}

echo "---Create manager-1"
docker-machine create $DRIVER_ARGS manager-1 || exit 1
manager_ip=$(getInternalIp manager-1)

echo "---Swarm Init"
docker-machine ssh manager-1 sudo docker swarm init --advertise-addr ${manager_ip} || exit 1
docker-machine ssh manager-1 sudo docker node update --label-add node.hostname=manager-1 manager-1

printf "\n---Get Tokens\n"
manager_token=$(docker-machine ssh manager-1 sudo docker swarm join-token -q manager)
worker_token=$(docker-machine ssh manager-1 sudo docker swarm join-token -q worker)

for n in {2..3} ; do
	name=manager-${n}
	printf "\n---Create ${name}\n"
	docker-machine create $DRIVER_ARGS ${name} || exit 1
	ip=$(getInternalIp ${name})
	echo "--- Swarm Manager Join"
	docker-machine ssh ${name} sudo docker swarm join --advertise-addr ${ip} --token ${manager_token} ${manager_ip}:2377 || exit 1
	docker-machine ssh ${name} sudo docker node update --label-add node.hostname=${name} ${name}
done

for n in {1..3} ; do
	name=worker-${n}
	printf "\n---Create ${name}\n"
	docker-machine create $DRIVER_ARGS ${name} || exit 1
	ip=$(getInternalIp ${name})
	echo "--- Swarm Worker Join"
	docker-machine ssh ${name} sudo docker swarm join --advertise-addr ${ip} --token ${worker_token} ${manager_ip}:2377 || exit 1
	docker-machine ssh manager-1 sudo docker node update --label-add node.hostname=${name} ${name}
done

printf "\n\n------------------------------------\n"
echo "To connect to your cluster..."
echo 'eval $(docker-machine env manager-1)'
